import type { MockEvent } from '@/types/mock'

// ===== 25+ رویداد واقعی و جذاب ایرانی =====
export const mockEvents: MockEvent[] = [
  {
    id: '1',
    title: 'جشنواره فیلم فجر',
    slug: 'fajr-film-festival',
    city: 'تهران',
    type: 'هنری',
    style: 'جشنواره',
    startDate: '۱۷ بهمن',
    endDate: '۲۵ بهمن',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
    shortDescription: 'بزرگ‌ترین رویداد سینمایی ایران با نمایش بهترین آثار سینمای ملی',
    featured: true,
    emoji: '🎬',
  },
  {
    id: '2',
    title: 'جشن نوروز ۱۴۰۴',
    slug: 'nowruz-2025',
    city: 'سراسر ایران',
    type: 'ملی',
    style: 'جشنواره',
    startDate: '۱ فروردین',
    endDate: '۱۳ فروردین',
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800',
    shortDescription: 'جشن باستانی نوروز با هفت‌سین، دیدوبازدیدها و سنت‌های کهن ایرانی',
    featured: true,
    emoji: '🎊',
  },
  {
    id: '3',
    title: 'جشنواره گلاب‌گیری کاشان',
    slug: 'kashan-rosewater',
    city: 'کاشان',
    type: 'فرهنگی',
    style: 'جشنواره',
    startDate: '۱۵ اردیبهشت',
    endDate: '۲۵ اردیبهشت',
    image: 'https://images.unsplash.com/photo-1584286595398-a59f21d7f1e0?w=800',
    shortDescription: 'جشن گل محمدی و گلاب‌گیری سنتی در قمصر کاشان با موسیقی محلی',
    featured: true,
    emoji: '🌹',
  },
  {
    id: '4',
    title: 'شب یلدا',
    slug: 'yalda-night',
    city: 'سراسر ایران',
    type: 'ملی',
    style: 'فرهنگی',
    startDate: '۳۰ آذر',
    endDate: '۳۰ آذر',
    image: 'https://images.unsplash.com/photo-1544118407-1c4611e4e5ad?w=800',
    shortDescription: 'طولانی‌ترین شب سال با هندوانه، انار، آجیل و دورهمی خانوادگی',
    featured: true,
    emoji: '🌙',
  },
  {
    id: '5',
    title: 'محرم و عاشورا',
    slug: 'muharram-ashura',
    city: 'سراسر ایران',
    type: 'مذهبی',
    style: 'مذهبی',
    startDate: '۱ محرم',
    endDate: '۱۰ محرم',
    image: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800',
    shortDescription: 'مراسم عزاداری امام حسین (ع) با دسته‌های عزاداری و نذری',
    featured: false,
    emoji: '⚔️',
  },
  {
    id: '6',
    title: 'جشنواره موسیقی فجر',
    slug: 'fajr-music-festival',
    city: 'تهران',
    type: 'هنری',
    style: 'جشنواره',
    startDate: '۱۰ بهمن',
    endDate: '۲۲ بهمن',
    image: 'https://images.unsplash.com/photo-1501612780327-45045538702b?w=800',
    shortDescription: 'بزرگ‌ترین رویداد موسیقی ایران با اجرای هنرمندان مطرح',
    featured: false,
    emoji: '🎵',
  },
  {
    id: '7',
    title: 'چهارشنبه سوری',
    slug: 'chaharshanbe-suri',
    city: 'سراسر ایران',
    type: 'ملی',
    style: 'فرهنگی',
    startDate: '۲۸ اسفند',
    endDate: '۲۸ اسفند',
    image: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=800',
    shortDescription: 'آخرین چهارشنبه سال با آتش‌افروزی و پرش از آتش',
    featured: true,
    emoji: '🔥',
  },
  {
    id: '8',
    title: 'سیزده‌به‌در',
    slug: 'sizdah-bedar',
    city: 'سراسر ایران',
    type: 'ملی',
    style: 'فرهنگی',
    startDate: '۱۳ فروردین',
    endDate: '۱۳ فروردین',
    image: 'https://images.unsplash.com/photo-1542909168-82c3e7fdca44?w=800',
    shortDescription: 'روز طبیعت‌گردی و پیک‌نیک در فضای سبز با خانواده',
    featured: false,
    emoji: '🌱',
  },
  {
    id: '9',
    title: 'جشنواره تئاتر فجر',
    slug: 'fajr-theater-festival',
    city: 'تهران',
    type: 'هنری',
    style: 'جشنواره',
    startDate: '۱۵ بهمن',
    endDate: '۲۵ بهمن',
    image: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=800',
    shortDescription: 'بهترین آثار تئاتر ایران در سالن‌های مختلف پایتخت',
    featured: false,
    emoji: '🎭',
  },
  {
    id: '10',
    title: 'نمایشگاه کتاب تهران',
    slug: 'tehran-book-fair',
    city: 'تهران',
    type: 'فرهنگی',
    style: 'نمایشگاه',
    startDate: '۱۵ اردیبهشت',
    endDate: '۲۶ اردیبهشت',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
    shortDescription: 'بزرگ‌ترین نمایشگاه کتاب خاورمیانه در مصلی امام خمینی',
    featured: false,
    emoji: '📚',
  },
  {
    id: '11',
    title: 'جشنواره انار یزد',
    slug: 'yazd-pomegranate-festival',
    city: 'یزد',
    type: 'فرهنگی',
    style: 'جشنواره',
    startDate: '۲۰ آبان',
    endDate: '۲۵ آبان',
    image: 'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=800',
    shortDescription: 'جشن برداشت انار با نمایش محصولات و غذاهای سنتی',
    featured: false,
    emoji: '🍎',
  },
  {
    id: '12',
    title: 'جشنواره فرهنگ اقوام',
    slug: 'ethnic-culture-festival',
    city: 'تهران',
    type: 'فرهنگی',
    style: 'جشنواره',
    startDate: '۱۰ خرداد',
    endDate: '۲۰ خرداد',
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
    shortDescription: 'نمایش فرهنگ اقوام مختلف ایران با موسیقی و صنایع دستی',
    featured: false,
    emoji: '🎪',
  },
  {
    id: '13',
    title: 'جشنواره خرما بوشهر',
    slug: 'bushehr-date-festival',
    city: 'بوشهر',
    type: 'فرهنگی',
    style: 'جشنواره',
    startDate: '۱۰ شهریور',
    endDate: '۱۵ شهریور',
    image: 'https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=800',
    shortDescription: 'جشن برداشت خرما و نمایش انواع خرمای ایرانی',
    featured: false,
    emoji: '🌴',
  },
  {
    id: '14',
    title: 'جشنواره عکس تهران',
    slug: 'tehran-photo-festival',
    city: 'تهران',
    type: 'هنری',
    style: 'نمایشگاه',
    startDate: '۵ دی',
    endDate: '۱۵ دی',
    image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800',
    shortDescription: 'نمایشگاه آثار عکاسان برجسته ایرانی و بین‌المللی',
    featured: false,
    emoji: '📷',
  },
  {
    id: '15',
    title: 'جشنواره گردشگری کیش',
    slug: 'kish-tourism-festival',
    city: 'کیش',
    type: 'گردشگری',
    style: 'جشنواره',
    startDate: '۱ مهر',
    endDate: '۱۰ مهر',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    shortDescription: 'جشنواره تابستانی کیش با ورزش‌های آبی و تفریحات ساحلی',
    featured: false,
    emoji: '🏖️',
  },
  {
    id: '16',
    title: 'اربعین حسینی',
    slug: 'arbaeen',
    city: 'کربلا (عراق)',
    type: 'مذهبی',
    style: 'مذهبی',
    startDate: '۲۰ صفر',
    endDate: '۲۰ صفر',
    image: 'https://images.unsplash.com/photo-1564769610851-d34896c6e8f8?w=800',
    shortDescription: 'بزرگ‌ترین راهپیمایی جهان به سمت کربلا در اربعین امام حسین',
    featured: false,
    emoji: '🕌',
  },
  {
    id: '17',
    title: 'جشنواره قالیشویان تبریز',
    slug: 'tabriz-carpet-washing',
    city: 'تبریز',
    type: 'فرهنگی',
    style: 'سنتی',
    startDate: '۱۵ مرداد',
    endDate: '۱۶ مرداد',
    image: 'https://images.unsplash.com/photo-1601298862042-b8da1fb87c88?w=800',
    shortDescription: 'سنت قالیشویی در رودخانه با موسیقی و شادی',
    featured: false,
    emoji: '🧵',
  },
  {
    id: '18',
    title: 'جشنواره پسته رفسنجان',
    slug: 'rafsanjan-pistachio-festival',
    city: 'رفسنجان',
    type: 'فرهنگی',
    style: 'جشنواره',
    startDate: '۲۰ شهریور',
    endDate: '۲۵ شهریور',
    image: 'https://images.unsplash.com/photo-1591963976403-47fb50a41c67?w=800',
    shortDescription: 'جشن برداشت پسته با نمایش محصولات و غذاهای محلی',
    featured: false,
    emoji: '🥜',
  },
  {
    id: '19',
    title: 'جشنواره شقایق شاهرود',
    slug: 'shahrood-poppy-festival',
    city: 'شاهرود',
    type: 'طبیعت‌گردی',
    style: 'گردشگری',
    startDate: '۱۵ اردیبهشت',
    endDate: '۲۵ اردیبهشت',
    image: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    shortDescription: 'تماشای دشت‌های شقایق وحشی در کویر شاهرود',
    featured: false,
    emoji: '🌺',
  },
  {
    id: '20',
    title: 'جشنواره فیلم کوتاه تهران',
    slug: 'tehran-short-film-festival',
    city: 'تهران',
    type: 'هنری',
    style: 'جشنواره',
    startDate: '۱۵ آبان',
    endDate: '۲۲ آبان',
    image: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800',
    shortDescription: 'نمایش بهترین فیلم‌های کوتاه ایرانی و بین‌المللی',
    featured: false,
    emoji: '🎥',
  },
  {
    id: '21',
    title: 'جشنواره زعفران قاینات',
    slug: 'qayen-saffron-festival',
    city: 'قاینات',
    type: 'فرهنگی',
    style: 'جشنواره',
    startDate: '۱۵ آبان',
    endDate: '۲۰ آبان',
    image: 'https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=800',
    shortDescription: 'جشن برداشت طلای سرخ با نمایش کشاورزی سنتی',
    featured: false,
    emoji: '🌾',
  },
  {
    id: '22',
    title: 'جشنواره آب انار',
    slug: 'pomegranate-juice-festival',
    city: 'سیرجان',
    type: 'فرهنگی',
    style: 'جشنواره',
    startDate: '۱۰ مهر',
    endDate: '۱۵ مهر',
    image: 'https://images.unsplash.com/photo-1571336420178-2e647e2df35c?w=800',
    shortDescription: 'جشن برداشت انار با نمایش آب‌گیری سنتی',
    featured: false,
    emoji: '🍹',
  },
  {
    id: '23',
    title: 'جشنواره عشایر فارس',
    slug: 'fars-nomads-festival',
    city: 'شیراز',
    type: 'فرهنگی',
    style: 'سنتی',
    startDate: '۵ خرداد',
    endDate: '۱۰ خرداد',
    image: 'https://images.unsplash.com/photo-1536431311719-398b6704d4cc?w=800',
    shortDescription: 'نمایش فرهنگ عشایر قشقایی با موسیقی و صنایع دستی',
    featured: false,
    emoji: '🏕️',
  },
  {
    id: '24',
    title: 'جشنواره ورزش‌های سنتی',
    slug: 'traditional-sports-festival',
    city: 'تهران',
    type: 'ورزشی',
    style: 'ورزشی',
    startDate: '۱۰ مرداد',
    endDate: '۱۵ مرداد',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800',
    shortDescription: 'نمایش ورزش‌های باستانی ایران مثل کشتی پهلوانی و زورخانه',
    featured: false,
    emoji: '🤼',
  },
  {
    id: '25',
    title: 'جشنواره هنرهای نمایشی اصفهان',
    slug: 'isfahan-performing-arts',
    city: 'اصفهان',
    type: 'هنری',
    style: 'جشنواره',
    startDate: '۲۰ شهریور',
    endDate: '۲۸ شهریور',
    image: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800',
    shortDescription: 'نمایش بهترین آثار تئاتر، موسیقی و رقص در نصف جهان',
    featured: false,
    emoji: '🎨',
  },
]

// ===== فیلتر کردن رویدادهای ویژه =====
export const getFeaturedEvents = () => {
  return mockEvents.filter((event) => event.featured)
}

// ===== فیلتر بر اساس شهر =====
export const getEventsByCity = (city: string) => {
  if (city === 'همه شهرها') return mockEvents
  return mockEvents.filter((event) => event.city === city)
}

// ===== فیلتر بر اساس نوع =====
export const getEventsByType = (type: string) => {
  return mockEvents.filter((event) => event.type === type)
}
