import { PrismaClient, EventStyle, EventType, FixedVariable, EventStatus } from '@prisma/client'

const prisma = new PrismaClient()

export const sampleEvents = [
  {
    title: 'جشنواره فیلم فجر ۱۴۰۴',
    slug: 'jashnvareh-film-fajr-1404',
    style: EventStyle.FESTIVAL,
    type: EventType.ARTISTIC,
    fixedOrVariable: FixedVariable.FIXED,
    country: 'Iran',
    city: 'تهران',
    venue: 'پردیس ملت',
    address: 'تهران، خیابان ولیعصر، پردیس سینمایی ملت',
    latitude: 35.7219,
    longitude: 51.4231,
    dateRangeText: '17 تا 25 بهمن 1404',
    startDate: new Date('2026-02-06'),
    endDate: new Date('2026-02-14'),
    registrationDeadline: new Date('2026-02-01'),
    durationText: '9 روز',
    basePrice: 50000,
    currency: 'IRR',
    maxCapacity: 500,
    availableSpots: 500,
    isBookable: true,
    shortDescription: 'بزرگترین رویداد سینمایی کشور با حضور فیلم‌سازان برتر',
    description: `جشنواره فیلم فجر بزرگترین و مهم‌ترین رویداد سینمایی ایران است که هر ساله در بهمن ماه برگزار می‌شود.

ویژگی‌های جشنواره:
- نمایش بیش از 100 فیلم بلند و کوتاه
- حضور کارگردانان و بازیگران مطرح
- مراسم اختتامیه با اهدای جوایز
- نشست‌های تخصصی سینمایی`,
    opportunities: '- دیدن فیلم‌های جدید قبل از اکران عمومی\n- فرصت گفتگو با فیلمسازان\n- شرکت در نشست‌های تخصصی',
    challenges: '- شلوغی پردیس‌ها در ساعات اوج\n- نیاز به خرید بلیط زودهنگام',
    featuredImage: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800',
    images: [
      'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800',
      'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
    ],
    organizerName: 'دبیرخانه جشنواره فیلم فجر',
    organizerPhone: '02188754321',
    organizerEmail: 'info@fajrfestival.ir',
    website: 'https://fajrfestival.ir',
    status: EventStatus.APPROVED,
    keywords: ['سینما', 'فیلم', 'جشنواره', 'فجر', 'تهران'],
    publishedAt: new Date(),
  },
  {
    title: 'نمایشگاه کتاب تهران ۱۴۰۴',
    slug: 'namayeshgah-ketab-tehran-1404',
    style: EventStyle.EXHIBITION,
    type: EventType.ARTISTIC,
    fixedOrVariable: FixedVariable.FIXED,
    country: 'Iran',
    city: 'تهران',
    venue: 'مصلی امام خمینی',
    address: 'تهران، نیایش، مصلی امام خمینی',
    latitude: 35.7355,
    longitude: 51.2939,
    dateRangeText: '1 تا 14 اردیبهشت 1404',
    startDate: new Date('2025-04-21'),
    endDate: new Date('2025-05-04'),
    durationText: '14 روز',
    basePrice: 0,
    maxCapacity: 10000,
    availableSpots: 10000,
    isBookable: true,
    shortDescription: 'بزرگترین رویداد فرهنگی و نشر کتاب در ایران',
    description: `نمایشگاه بین‌المللی کتاب تهران با حضور بیش از ۳۰۰۰ ناشر از سراسر کشور و جهان برگزار می‌شود.

امکانات:
- نمایش و فروش میلیون‌ها عنوان کتاب
- نشست‌ها و رونمایی کتاب
- برنامه‌های ویژه کودکان و نوجوانان`,
    featuredImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800',
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800'],
    organizerName: 'وزارت فرهنگ و ارشاد اسلامی',
    organizerEmail: 'info@tibf.ir',
    website: 'https://tibf.ir',
    status: EventStatus.APPROVED,
    keywords: ['کتاب', 'نمایشگاه', 'فرهنگ', 'نشر', 'تهران'],
    publishedAt: new Date(),
  },
  {
    title: 'جشن نوروز ۱۴۰۵',
    slug: 'jashn-nowruz-1405',
    style: EventStyle.FESTIVAL,
    type: EventType.NATIONAL,
    fixedOrVariable: FixedVariable.FIXED,
    country: 'Iran',
    city: 'سراسر ایران',
    venue: 'سراسر کشور',
    dateRangeText: '1 تا 13 فروردین 1405',
    startDate: new Date('2026-03-21'),
    endDate: new Date('2026-04-02'),
    durationText: '13 روز',
    basePrice: 0,
    isBookable: false,
    shortDescription: 'جشن باستانی آغاز سال نو ایرانی با هفت‌سین و رسوم سنتی',
    description: `نوروز بزرگ‌ترین جشن ملی ایرانیان است که با تحویل سال و آغاز بهار جشن گرفته می‌شود. این جشن باستانی با سابقه‌ای چند هزار ساله، در فهرست میراث معنوی یونسکو ثبت شده است.

خانه‌تکانی، خرید لباس نو، چیدن سفره هفت‌سین، دید و بازدید با بستگان و سیزده‌به‌در از آداب و رسوم نوروزی است.`,
    featuredImage: 'https://images.unsplash.com/photo-1520034475321-cbe63696469a?w=800',
    images: ['https://images.unsplash.com/photo-1520034475321-cbe63696469a?w=800'],
    organizerName: 'سازمان میراث فرهنگی',
    status: EventStatus.APPROVED,
    keywords: ['نوروز', 'عید', 'بهار', 'هفت‌سین', 'سال نو'],
    publishedAt: new Date(),
  },
  {
    title: 'شب یلدا ۱۴۰۴',
    slug: 'shab-yalda-1404',
    style: EventStyle.OTHER,
    type: EventType.NATIONAL,
    fixedOrVariable: FixedVariable.FIXED,
    country: 'Iran',
    city: 'سراسر ایران',
    venue: 'خانه‌های ایرانی و مراکز فرهنگی',
    dateRangeText: '30 آذر 1404',
    startDate: new Date('2025-12-21'),
    endDate: new Date('2025-12-21'),
    durationText: '1 شب',
    basePrice: 0,
    isBookable: false,
    shortDescription: 'بلندترین شب سال با هندوانه، انار و فال حافظ',
    description: `شب یلدا بلندترین شب سال است. خانواده‌ها دور هم جمع می‌شوند و با خوردن هندوانه و انار، از دیوان حافظ فال می‌گیرند.`,
    featuredImage: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
    images: ['https://images.unsplash.com/photo-1542838132-92c53300491e?w=800'],
    organizerName: 'سازمان میراث فرهنگی',
    status: EventStatus.APPROVED,
    keywords: ['یلدا', 'شب چله', 'حافظ', 'هندوانه', 'انار'],
    publishedAt: new Date(),
  },
  {
    title: 'جشن گلاب‌گیری کاشان',
    slug: 'jashn-golabgiri-kashan',
    style: EventStyle.FESTIVAL,
    type: EventType.TOURISM,
    fixedOrVariable: FixedVariable.FIXED,
    country: 'Iran',
    city: 'کاشان',
    venue: 'روستای قمصر',
    address: 'کاشان، روستای قمصر، باغ‌های گل محمدی',
    latitude: 33.9831,
    longitude: 51.4364,
    dateRangeText: '1 تا 15 اردیبهشت 1405',
    startDate: new Date('2026-04-21'),
    endDate: new Date('2026-05-05'),
    durationText: '15 روز',
    basePrice: 0,
    isBookable: false,
    shortDescription: 'جشنواره سنتی گلاب‌گیری با عطر گل محمدی',
    description: `جشن گلاب‌گیری کاشان یکی از زیباترین جشن‌های سنتی ایران است. در این جشن فرآیند سنتی تقطیر گل محمدی و تولید گلاب به نمایش گذاشته می‌شود.`,
    featuredImage: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    images: ['https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800'],
    organizerName: 'اداره میراث فرهنگی کاشان',
    organizerPhone: '03155423030',
    status: EventStatus.APPROVED,
    keywords: ['گلاب', 'کاشان', 'قمصر', 'گل محمدی', 'سنتی'],
    publishedAt: new Date(),
  },
  {
    title: 'محرم و عاشورا ۱۴۰۴',
    slug: 'muharram-ashura-1404',
    style: EventStyle.RELIGIOUS,
    type: EventType.RELIGIOUS,
    fixedOrVariable: FixedVariable.VARIABLE,
    country: 'Iran',
    city: 'سراسر ایران',
    venue: 'مساجد و حسینیه‌ها',
    dateRangeText: 'محرم 1447 هجری قمری',
    startDate: new Date('2025-07-07'),
    endDate: new Date('2025-07-16'),
    durationText: '10 روز',
    basePrice: 0,
    isBookable: false,
    shortDescription: 'مراسم سوگواری امام حسین (ع) در سراسر ایران',
    description: `ماه محرم و به ویژه روز عاشورا، یکی از مهم‌ترین مناسبت‌های مذهبی در ایران است. هیئت‌های مذهبی، نوحه‌خوانی و تعزیه‌خوانی برگزار می‌شود.`,
    featuredImage: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    images: ['https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800'],
    organizerName: 'هیئت‌های مذهبی',
    status: EventStatus.APPROVED,
    keywords: ['محرم', 'عاشورا', 'مذهبی', 'عزاداری', 'حسینی'],
    publishedAt: new Date(),
  },
  {
    title: 'همایش ملی نوآوری و فناوری',
    slug: 'hamayesh-noavari-fanavari',
    style: EventStyle.CONFERENCE,
    type: EventType.SCIENTIFIC,
    fixedOrVariable: FixedVariable.FIXED,
    country: 'Iran',
    city: 'تهران',
    venue: 'مرکز همایش‌های برج میلاد',
    address: 'تهران، همت غربی، برج میلاد',
    latitude: 35.7447,
    longitude: 51.3753,
    dateRangeText: '15 و 16 خرداد 1404',
    startDate: new Date('2025-06-05'),
    endDate: new Date('2025-06-06'),
    durationText: '2 روز',
    basePrice: 250000,
    maxCapacity: 300,
    availableSpots: 250,
    isBookable: true,
    shortDescription: 'همایش ملی نوآوری و فناوری با حضور متخصصان برتر',
    description: `این همایش با هدف گردهمایی فعالان حوزه فناوری، استارتاپ‌ها و سرمایه‌گذاران برگزار می‌شود.

محورها: هوش مصنوعی، بلاکچین، اینترنت اشیا، امنیت سایبری`,
    featuredImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    images: ['https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800'],
    organizerName: 'انجمن نوآوری ایران',
    organizerPhone: '02144556677',
    organizerEmail: 'info@innoconf.ir',
    website: 'https://innoconf.ir',
    status: EventStatus.APPROVED,
    keywords: ['همایش', 'فناوری', 'نوآوری', 'استارتاپ'],
    publishedAt: new Date(),
  },
  {
    title: 'جشنواره موسیقی فجر ۱۴۰۴',
    slug: 'jashnvareh-musiqi-fajr-1404',
    style: EventStyle.FESTIVAL,
    type: EventType.ARTISTIC,
    fixedOrVariable: FixedVariable.FIXED,
    country: 'Iran',
    city: 'تهران',
    venue: 'تالار وحدت',
    address: 'تهران، خیابان حافظ، تالار وحدت',
    latitude: 35.6949,
    longitude: 51.4055,
    dateRangeText: '20 تا 28 بهمن 1404',
    startDate: new Date('2026-02-09'),
    endDate: new Date('2026-02-17'),
    durationText: '9 روز',
    basePrice: 75000,
    maxCapacity: 800,
    availableSpots: 700,
    isBookable: true,
    shortDescription: 'جشنواره موسیقی فجر با اجرای هنرمندان برجسته',
    description: `سی و نهمین دوره جشنواره موسیقی فجر با اجرای بیش از 50 گروه و خواننده برتر موسیقی ایرانی.

سبک‌ها: موسیقی سنتی، پاپ، کلاسیک، محلی`,
    featuredImage: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    images: ['https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800'],
    organizerName: 'اداره کل موسیقی',
    organizerEmail: 'info@fajrmusic.ir',
    website: 'https://fajrmusic.ir',
    status: EventStatus.APPROVED,
    keywords: ['موسیقی', 'جشنواره', 'کنسرت', 'فجر'],
    publishedAt: new Date(),
  },
  {
    title: 'تور طبیعت‌گردی جنگل‌های شمال',
    slug: 'tour-jangal-shomal',
    style: EventStyle.TOURISM,
    type: EventType.TOURISM,
    fixedOrVariable: FixedVariable.VARIABLE,
    country: 'Iran',
    city: 'رشت',
    venue: 'جنگل‌های گیلان',
    address: 'استان گیلان، رشت',
    latitude: 37.2808,
    longitude: 49.5832,
    dateRangeText: 'هر هفته پنج‌شنبه و جمعه',
    startDate: new Date('2025-03-21'),
    endDate: new Date('2025-06-21'),
    durationText: '2 روز و 1 شب',
    basePrice: 1200000,
    maxCapacity: 20,
    availableSpots: 15,
    isBookable: true,
    shortDescription: 'تجربه سفر به یاد ماندنی در دل جنگل‌های شمال',
    description: `پیاده‌روی در مسیرهای جنگلی، بازدید از آبشارها و اقامت در کلبه‌های چوبی.`,
    featuredImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    images: ['https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800'],
    organizerName: 'آژانس سفرهای سبز',
    organizerPhone: '09123456789',
    organizerEmail: 'info@greentrips.ir',
    status: EventStatus.APPROVED,
    keywords: ['طبیعت‌گردی', 'تور', 'جنگل', 'شمال', 'گیلان'],
    publishedAt: new Date(),
  },
  {
    title: 'جشنواره پاییزی اصفهان',
    slug: 'jashnvareh-paeizi-isfahan',
    style: EventStyle.FESTIVAL,
    type: EventType.TOURISM,
    fixedOrVariable: FixedVariable.FIXED,
    country: 'Iran',
    city: 'اصفهان',
    venue: 'میدان نقش جهان',
    address: 'اصفهان، میدان نقش جهان',
    latitude: 32.6546,
    longitude: 51.6680,
    dateRangeText: '10 تا 20 مهر 1404',
    startDate: new Date('2025-10-02'),
    endDate: new Date('2025-10-12'),
    durationText: '10 روز',
    basePrice: 0,
    isBookable: false,
    shortDescription: 'جشنواره فرهنگی و هنری پاییز در اصفهان',
    description: `جشنواره پاییزی اصفهان با اجراهای موسیقی سنتی، نمایش صنایع دستی و تورهای گردشگری برگزار می‌شود.`,
    featuredImage: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
    images: ['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800'],
    organizerName: 'سازمان فرهنگی اصفهان',
    status: EventStatus.APPROVED,
    keywords: ['اصفهان', 'پاییز', 'جشنواره', 'فرهنگی', 'نقش جهان'],
    publishedAt: new Date(),
  },
  {
    title: 'نمایشگاه صنایع دستی یزد',
    slug: 'namayeshgah-sanaye-dasti-yazd',
    style: EventStyle.EXHIBITION,
    type: EventType.ARTISTIC,
    fixedOrVariable: FixedVariable.FIXED,
    country: 'Iran',
    city: 'یزد',
    venue: 'میدان امیرچخماق',
    address: 'یزد، میدان امیرچخماق',
    latitude: 31.8974,
    longitude: 54.3569,
    dateRangeText: '1 تا 10 شهریور 1404',
    startDate: new Date('2025-08-23'),
    endDate: new Date('2025-09-01'),
    durationText: '10 روز',
    basePrice: 0,
    isBookable: false,
    shortDescription: 'نمایشگاه صنایع دستی سنتی شهر کهن یزد',
    description: `قالی‌بافی، سفالگری، بافت ترمه، زیلوبافی و شیرینی‌های سنتی یزد در این نمایشگاه به نمایش درمی‌آید.`,
    featuredImage: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800',
    images: ['https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800'],
    organizerName: 'اداره میراث فرهنگی یزد',
    status: EventStatus.APPROVED,
    keywords: ['صنایع دستی', 'یزد', 'نمایشگاه', 'سنتی'],
    publishedAt: new Date(),
  },
  {
    title: 'جشنواره حافظ شیراز',
    slug: 'jashnvareh-hafez-shiraz',
    style: EventStyle.FESTIVAL,
    type: EventType.ARTISTIC,
    fixedOrVariable: FixedVariable.FIXED,
    country: 'Iran',
    city: 'شیراز',
    venue: 'حافظیه شیراز',
    address: 'شیراز، بلوار حافظ، حافظیه',
    latitude: 29.6187,
    longitude: 52.5340,
    dateRangeText: '20 تا 25 آبان 1404',
    startDate: new Date('2025-11-11'),
    endDate: new Date('2025-11-16'),
    durationText: '5 روز',
    basePrice: 30000,
    maxCapacity: 200,
    availableSpots: 150,
    isBookable: true,
    shortDescription: 'بزرگداشت حافظ شیرازی با شعرخوانی و موسیقی',
    description: `شعرخوانی از دیوان حافظ، موسیقی سنتی و نشست‌های تخصصی درباره اشعار حافظ.`,
    featuredImage: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800',
    images: ['https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800'],
    organizerName: 'اداره فرهنگ و ارشاد شیراز',
    status: EventStatus.APPROVED,
    keywords: ['حافظ', 'شیراز', 'شعر', 'ادبیات', 'فرهنگی'],
    publishedAt: new Date(),
  },
]

async function seedEvents() {
  for (const eventData of sampleEvents) {
    await prisma.event.upsert({
      where: { slug: eventData.slug },
      update: eventData,
      create: eventData,
    })
    console.log(`  ✓ ${eventData.title}`)
  }

  console.log('✅ Events seeded successfully')
}

export default seedEvents
